POST http://localhost:5000/user/register
Content-Type: application/json

{
    "email" : "vanhieu3668@gmail.com", 
    "password" : "A11223344"
}
###
GET https://bit.ly/tiengruoi


###
GET https://league99.herokuapp.com/api/sports/england/charts/0
### 
GET http://localhost:5000/user/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZhbmhpZXUzNjY4QGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDROWkI0dkh2ZE1XSGh1dUIvL0NRQmVBby9lWG9IdXJqZ2RvNXVXazdubXZVcHdJUGZYbXNLIiwiaWF0IjoxNjYwODM0OTE5LCJleHAiOjE2NjA4NDIxMTl9.UcW6Xz0bitKIf_9yJe1kDkc7ZssP5NAxLCJvsyG2I8M
###
GET http://localhost:5000/user/activate/sadfasdfet
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email" : "vanhieu3668@gmail.com", 
    "password" : "A11223344"
}

###
POST http://localhost:5000/user/save/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjQzNWYyNmMxZjRkMzk0MGNhNjAzMyIsImlhdCI6MTYyNjYxNzM3MywiZXhwIjoxNjI2NzkwMTczfQ.FL3gJyBCtnL2myfKZQBQy9a5VWITHYZdcLOifWfRVns
Content-Type: application/json

{
    "userName" : "hieupc92", 
    "number" : "0979834521", 
    "address" : {
        "main" : "hanoi", 
        "des" : "canh ho ba be"
    }
}  

###
POST http://localhost:5000/update 
Content-type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjQzNWYyNmMxZjRkMzk0MGNhNjAzMyIsImlhdCI6MTYyNzA1MjkyOCwiZXhwIjoxNjI3MjI1NzI4fQ.9wRpGlEoEQByumiRKnSyjA3VcZp7hb5Us8iUZpyIPws

{
    "name" : "hieupc", 
    "pasow" : "akdjfier"
}

###
POST http://localhost:5000/user/update?_method=put
Content-Type: application/json

{
    "email" : "vuhieukenny2@gmail.com", 
    "password" : "11223344"
}

###
POST http://localhost:5000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjQzNWYyNmMxZjRkMzk0MGNhNjAzMyIsImlhdCI6MTYyNjk2NjIzNSwiZXhwIjoxNjI3MTM5MDM1fQ.6zs8OJw0Jt--GAbBLfkjhVokT4A8z97f-EENZPY1YwQ

{
    "name" : "đồng hồ nam, đồng hồ , phụ kiện", 
    "des" : "phụ kiện"
}

###
GET http://localhost:5000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjQzNWYyNmMxZjRkMzk0MGNhNjAzMyIsImlhdCI6MTYyNjk2NTQ0NCwiZXhwIjoxNjI3MTM4MjQ0fQ.nYi_DJ3pW9xF37iUi-Yh0vajcK9FNexkIuo1O6U4ENg


### 
GET http://localhost:5000/api/products?num=10
Content-Type: application/json

### 
GET http://localhost:5000/user/refresh_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMGY0NGU4ZmZmZmQzM2QwYzljOWUzOCIsImlhdCI6MTYyODQwMzE3MCwiZXhwIjoxNjI4NDEwMzcwfQ.qarfdd8O6Ef4QHSMfkr48xUjP-kS51XhlauPAmj7sEk

###
GET http://localhost:5000/api/products/60f544e0db9bf7089c3cade0


### 
GET http://localhost:5000/api/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjQzNTkxNmMxZjRkMzk0MGNhNjAyYiIsImlhdCI6MTYyNjgyNjk4MywiZXhwIjoxNjI2OTk5NzgzfQ.1Xfubv6PCke0KJMnXGvhKXLbJb1WiGc6segBEGGtf3A

###
GET http://localhost:5000/api/cart/add/:id

###
GET http://localhost:5000/api/products/search?q=áo

###
GET http://localhost:5000/api/page/search?q=quần%20ống

###
GET http://localhost:5000/api/page/search?q=áo%20hồ&page=2

###
GET http://localhost:5000/api/slide?type=prize


###
GET http://localhost:5000/api/slide?type=relative&userId=60f435916c1f4d3940ca602b

###
GET http://localhost:5000/api/slide?type=saled&num=6

###
GET http://localhost:5000/api/products/60f55179db9bf7089c3cae3eadf

###
POST http://localhost:5000/api/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZjQzNWYyNmMxZjRkMzk0MGNhNjAzMyIsImlhdCI6MTYyNzM2NDIzMywiZXhwIjoxNjI3MzcxNDMzfQ.Uaz4AnZgFXIqLBz9B-oLUJ012cCP2-4gVpWlAgcG6Hk
Content-Type: application/json

{
    "userInfo" : "HieuPc", 
    "order" : "none"
}

###
GET http://localhost:5000/user/order 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDAyNjYxYjIyMzM4MWRhY2Q3ZmM4OCIsImlhdCI6MTYyNzQwNTA4NiwiZXhwIjoxNjI3NDEyMjg2fQ.atihA7l_T_g3WLYiYcrg0luJC7NCVQSmHvaqBCVD-sk
 
### 
POST http://localhost:5000/user/forget
Content-Type: application/json

{
    "email" : "hoanghieuss3344@gmail.com"
}

###
POST http://localhost:5000/user/forget/account/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGY0MzU5MTZjMWY0ZDM5NDBjYTYwMmIiLCJpYXQiOjE2Mjc2MDk2NTUsImV4cCI6MTYyNzYxMDI1NX0.PytV0wmSycNUWhz6n0qpzVEjsTFJvcm9_y0G5pNhdH8
Content-Type: application/json

{
    "password" : "04092001hh"
}

###
GET https://serverchat69.herokuapp.com/chat/read
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDc5NjE2OGFlMjBhMzE5YzBiNWU0NCIsImlhdCI6MTYyODI2OTU2MywiZXhwIjoxNjI4Mjc2NzYzfQ.LvsuiB9VUVioXMVaQ7cASJq0ykz2aHx1OrlrQo8oT2E

# {
#     "mes" : "The first comment"
# }

###
POST https://serverchat69.herokuapp.com/chat/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDc5NjE2OGFlMjBhMzE5YzBiNWU0NCIsImlhdCI6MTYyODI2OTU2MywiZXhwIjoxNjI4Mjc2NzYzfQ.LvsuiB9VUVioXMVaQ7cASJq0ykz2aHx1OrlrQo8oT2E

{
    "mes" : "The first comment"
}




### 
GET https://sheltered-headland-14034.herokuapp.com/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkZG5ld0VtYWlsbmV3MkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRYRy5ZVG12dnpBS2NMVzh6Ny9PT2l1LzdvbEhvV0FoVG44amtrM2hyVzVIMFRaN0hBaWs4cSIsImlhdCI6MTYyODA0MDQ0OCwiZXhwIjoxNjI4MDQ3NjQ4fQ.lGcscWiWAnnbrjWnmuEZFtaqoGc3RJRgE8PaT10ePf4
###
POST http://localhost:5000/service/destroy
Content-Type: application/json

{
    "public_id" : "shopfull/p7zvwdqotrrbwzntgd1a"
}

###
GET https://demoshop69.herokuapp.com/user/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVmYjQ2ODAwQHp3b2hvLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJGwzNzhIZ25NOEIuMFJWaVpyREgwR09JNmZIUjhZeGVuV09SVElqTVRmVVZvWEczN1VLc2x5IiwiaWF0IjoxNjI4NDg1ODczLCJleHAiOjE2Mjg0OTMwNzN9.m0J0GNauQjxcXiIhEIMwwHkt-MOwqcgTdCHKWhscBYc

### 
POST https://ankiweb.net/decks/select/did1587114675822
Cookie: ankiweb=eyJrIjogImNicXhCM293R2ZrdGVWU0siLCAiYyI6IDIsICJ0IjogMTYyODk1MDczOH0.kUoinib3uqpeLfi0qtKGf7sPQU0d8Xozq5Srjh77SVY

### 
POST https://ankiuser.net/study/getCards
Content-Type: application/json
Cookie: ankiweb=eyJrIjogImNicXhCM293R2ZrdGVWU0siLCAiYyI6IDIsICJ0IjogMTYyODk1MDczOH0.kUoinib3uqpeLfi0qtKGf7sPQU0d8Xozq5Srjh77SVY

### 
GET https://drive.google.com/u/2/get_video_info?docid=1cZKy4B14W8HZdaZ3wJt4MvhL-Y83kyO2&drive_originator_app=303


###
GET http://localhost:3000/user/info
Content-Type: application/json